version: '3.3'
services:
    jottacloud:
        container_name: jottacloud-cli
        environment:
            - JOTTA_TOKEN=YOUR_AUTH_KEY_GOES_HERE
            - JOTTA_DEVICE=YOUR_MACHINE_NAME_GOES HERE
            - JOTTA_SCANINTERVAL=10m #0 for realtime, 10m, 1h etc
            - LOCALTIME=Europe/Zurich
        volumes:
            - './:/data/jottad'
            - './.ignore:/data/jottad/.ignore'
            - './jottad.env:/data/jottad/jottad.env'
            - '/home/:/backup/home' #add lines like this for multiple back up folders
        image: bluet/jottacloud
